syntax="proto3";

package rta;

option go_package = "rta/proto/pb";

import "callgraph.proto";
import "ssa.proto";

// Need better name for this
message ReachableEntry {
    ssa.Function function = 1;
    bool address_taken = 2;
}

// RTAResult contains the results of an RTA analysis and the state
message RTAResult {
    callgraph.CallGraph call_graph = 1;

    // I am tempted to make this a map<string, ReachableEntry> so lookups are faster.
    repeated ReachableEntry reachable = 2;

    // TODO(brian) Runtime types, but for now we don't deal with Interfaces
}

message ListOfFunctions {
    repeated ssa.Function functions = 1;
}

message ListOfCallSites {
    repeated ssa.CallSite call_sites = 1;
}

message RTAState {
    ssa.Function reflect_value_call = 1;
    map<string, ListOfFunctions> addr_taken_funcs_by_sig = 2;
    map<string, ListOfCallSites> dyn_call_sites = 3;

    // TODO: Invoke site, ConcreteType, InterfaceType
}