syntax="proto3";

package ssa;

option go_package = "rta/proto/pb";

message Package {
    string name = 1;
    string path = 2;
}

message Function {
    // hash will be the canonical identifier for a function
    string hash = 1;

    string name = 2;
    string signature = 3;
    Package package = 4; 

    Function parent = 5;
    int32 anon_index = 6;
    string receiver = 7;
    string synthetic = 8;
    string referenced_by = 9;
}

message CallSite {
    string hash = 1;

    Function parent_function = 2;
    string signature = 3;
    int32 block_index = 4;
}
